"""Forex-focused Smart Money Concept and technical-analysis toolkit."""

from smc_ta.engine.confluence import (
    AnalysisResult,
    ConfluenceConfig,
    analyze_forex,
    build_smc_ta_features,
    generate_confluence_signals,
)
from smc_ta.engine.multitimeframe import MultiTimeframeConfig, MultiTimeframeResult, analyze_multi_timeframe
from smc_ta.backtest import BacktestConfig, BacktestResult, run_backtest
from smc_ta.broker import BrokerOrder, PaperBroker
from smc_ta.config import (
    LIVE_CONFIRMATION_PHRASE,
    ConfigValidationError,
    ConfigValidationReport,
    RuntimeConfig,
    assert_runtime_ready,
    validate_runtime_config,
)
from smc_ta.data import DataQualityConfig, DataQualityReport, validate_candle_quality
from smc_ta.dashboard import render_live_dashboard_html, write_dashboard, write_live_dashboard
from smc_ta.forwardtest import (
    DemoForwardConfig,
    DemoForwardReportBundle,
    DemoForwardResult,
    render_demo_forward_html_report,
    run_demo_forward_test,
    write_demo_forward_report_bundle,
)
from smc_ta.lifecycle import (
    LifecycleRecoveryConfig,
    LifecycleRecoveryReport,
    MemoryTradeLifecycleStore,
    SQLiteTradeLifecycleStore,
    TradeLifecycleError,
    TradeLifecycleRecord,
    TradeLifecycleStateMachine,
    recover_lifecycle_after_restart,
    write_lifecycle_recovery_report,
)
from smc_ta.live import DemoTradingBot
from smc_ta.monitoring import LiveMonitoringSnapshot, build_live_monitoring_snapshot
from smc_ta.news import TradingEconomicsApiError, TradingEconomicsCalendarSource, TradingEconomicsConfig
from smc_ta.ops import (
    CommandSecretSource,
    EnvFileSecretSource,
    EnvSecretSource,
    IncidentReportBundle,
    JsonSecretSource,
    LogrotateConfig,
    RuntimeLogConfig,
    SecretResolutionConfig,
    SecretResolutionReport,
    SupervisorConfig,
    configure_runtime_logging,
    resolve_runtime_secrets,
    write_incident_report_bundle,
    write_logrotate_config,
    write_secret_resolution_report,
    write_supervisor_artifacts,
)
from smc_ta.preflight import (
    PreflightCheck,
    PreflightConfig,
    PreflightReport,
    PreflightValidationError,
    assert_preflight_ready,
    run_preflight,
)
from smc_ta.reconciliation import (
    BrokerReconciler,
    MemoryPositionLedger,
    MemorySyncCheckpointStore,
    ReconciliationConfig,
    ReconciliationResult,
    RestartSyncConfig,
    RestartSyncReport,
    SQLitePositionLedger,
    SQLiteSyncCheckpointStore,
    sync_broker_state_after_restart,
    write_restart_sync_report,
)
from smc_ta.risk import PortfolioRiskConfig, PortfolioRiskDecision, PortfolioRiskManager, RiskConfig, RiskDecision, RiskManager
from smc_ta.safety import EmergencyStopConfig, EmergencyStopController, EmergencyStopResult
from smc_ta.strategy import StrategyProfile, get_strategy_profile, list_strategy_profiles
from smc_ta.visualization import ChartConfig, render_analysis_chart_html, render_analysis_chart_svg, write_analysis_chart
from smc_ta.walkforward import (
    WalkForwardCandidate,
    WalkForwardConfig,
    WalkForwardResult,
    run_walk_forward,
)

__all__ = [
    "AnalysisResult",
    "BacktestConfig",
    "BacktestResult",
    "BrokerOrder",
    "BrokerReconciler",
    "ChartConfig",
    "CommandSecretSource",
    "ConfluenceConfig",
    "ConfigValidationError",
    "ConfigValidationReport",
    "DataQualityConfig",
    "DataQualityReport",
    "DemoForwardConfig",
    "DemoForwardReportBundle",
    "DemoForwardResult",
    "DemoTradingBot",
    "EmergencyStopConfig",
    "EmergencyStopController",
    "EmergencyStopResult",
    "EnvFileSecretSource",
    "EnvSecretSource",
    "IncidentReportBundle",
    "JsonSecretSource",
    "LIVE_CONFIRMATION_PHRASE",
    "LifecycleRecoveryConfig",
    "LifecycleRecoveryReport",
    "LiveMonitoringSnapshot",
    "LogrotateConfig",
    "MemoryPositionLedger",
    "MemorySyncCheckpointStore",
    "MemoryTradeLifecycleStore",
    "MultiTimeframeConfig",
    "MultiTimeframeResult",
    "PaperBroker",
    "PortfolioRiskConfig",
    "PortfolioRiskDecision",
    "PortfolioRiskManager",
    "PreflightCheck",
    "PreflightConfig",
    "PreflightReport",
    "PreflightValidationError",
    "ReconciliationConfig",
    "ReconciliationResult",
    "RestartSyncConfig",
    "RestartSyncReport",
    "RiskConfig",
    "RiskDecision",
    "RuntimeLogConfig",
    "RiskManager",
    "RuntimeConfig",
    "SecretResolutionConfig",
    "SecretResolutionReport",
    "SQLitePositionLedger",
    "SQLiteSyncCheckpointStore",
    "SQLiteTradeLifecycleStore",
    "StrategyProfile",
    "SupervisorConfig",
    "TradingEconomicsApiError",
    "TradingEconomicsCalendarSource",
    "TradingEconomicsConfig",
    "TradeLifecycleError",
    "TradeLifecycleRecord",
    "TradeLifecycleStateMachine",
    "WalkForwardCandidate",
    "WalkForwardConfig",
    "WalkForwardResult",
    "analyze_forex",
    "analyze_multi_timeframe",
    "assert_preflight_ready",
    "assert_runtime_ready",
    "build_smc_ta_features",
    "build_live_monitoring_snapshot",
    "configure_runtime_logging",
    "generate_confluence_signals",
    "get_strategy_profile",
    "list_strategy_profiles",
    "run_backtest",
    "run_demo_forward_test",
    "run_preflight",
    "run_walk_forward",
    "recover_lifecycle_after_restart",
    "resolve_runtime_secrets",
    "sync_broker_state_after_restart",
    "render_analysis_chart_html",
    "render_analysis_chart_svg",
    "render_demo_forward_html_report",
    "render_live_dashboard_html",
    "validate_candle_quality",
    "validate_runtime_config",
    "write_analysis_chart",
    "write_dashboard",
    "write_demo_forward_report_bundle",
    "write_incident_report_bundle",
    "write_live_dashboard",
    "write_lifecycle_recovery_report",
    "write_logrotate_config",
    "write_restart_sync_report",
    "write_secret_resolution_report",
    "write_supervisor_artifacts",
]
